### PR TITLE
[Feature  #159594965] Add user login page

### PR DESCRIPTION
**Pull request by TheSteelGuy**
**Introduction**
This PR creates login where users can sign in to the platform
**Description of Task to be completed:**
Login form with two input fields

How to manually test

Clone this repository
navigate into the repository after cloning
type git checkout ft-user-login #159594965 to switch from master to this branch
navigate further in the UI directory open login.html page with your preferred browser

Relevant Screen Shot
login

### CODE REVIEW

**Comment by evamaina** [comment]
Looks nice

**Comment by jeffandeko** [comment]
its cool

**Comment by vmuthabuku** [comment]
nice ui  one but you have misspelled the word stackoverflow

**Comment by asheux** [comment]
Looks great. Perhaps, in the description you could use this guide questions
#### What does this PR do?

#### How should this be manually tested?

#### Any background information context you want to provide?

#### What are the relevant pivotal tracker stories?

**Comment by Gidraf** [comment]
Looks Great

**Comment by Tony-Ndichu** [comment]
I like the design and theme colors, maybe add an image somewhere?

**Pull request merged**
