### PR TITLE
[ft #159597425] add profile page

### PR DESCRIPTION
**Pull request by TheSteelGuy**
**Introduction**
This PR creates a profile page where users can view and edit their profile, view recent questions, questions with most answers, and the total questions they have asked on the platform
Description of Task to be completed:
A page with all the information about the user activity

**How to manually test**

- Clone this repository
- navigate into the repository after cloning
- type git checkout 159597425-user-profile-page to switch from master to this branch
- navigate further in the UI directory open profile.html page with your preferred browser

Relevant story
[Click here](https://www.pivotaltracker.com/n/projects/2189398/stories/159597425)

Relevant Screen Shot

profile
prof2

### CODE REVIEW

**Comment by Adoniswalker** [comment]
Ui is good, where are the number of questions and answers given by the user?

**Comment by mmosoroohh** [comment]
your UI looks really great

**Comment by Enockkenya** [comment]
nyc

**Comment by TheSteelGuy** [comment]
@Adoniswalker  the label total questions is the number of questions and the answers given by a user are next to each question, in order to see the answers to a question; you must click the question..... I hope that is okay if not bring your perspective onto the table for adoption kindly,

**Pull request merged**
